class EnglishLanguagePlugin extends LanguagePlugin {
    async getAllData() {
        return {
            home: {
                title: "iComic",
            },
            library: {
                title: "Library",
                empty: "Please scan the library first",
                scan: "Scan",
                continue: "Continue reading",
                not_parsed: "Not parsed",
                all_files: "All files",
                not_parsed_file: "This file hasn't been parsed yet",
                select_parse_plugin: "Please select a parser plugin",
                parse: "Parse",
                select_chapter: "Select chapter",
                start_read: "Start reading",
                status_not_parsed: "Not parsed",
                status_parsing: "Parsing",
                status_parsed: "Parsed",
                status_parse_failed: "Parse failed",
            },
            download: {
                title: "Search",
                search: "Search",
                searching: "Searching for {query}",
                no_result: "No results found for {query}",
                standby: "Always something to read",
                cover: "Cover",
                detail: "Details",
                col_title: "Title",
                col_description: "Description",
                add_to_col: "Action",
                add_to_task: "Add",
            },
            reader: {
                loading_title: "Loading",
                loading_description: "Page is loading, please wait!",
                loading_error_title: "Load failed",
                loading_error_description: "Page load failed: {error}",
            },
            download_task: {
                title: "Tasks",
                col_name: "Name",
                col_progress: "Progress",
                col_info: "Info",
                col_action: "Action",
                col_status: "Status",
                col_status_wait: "Waiting",
                col_status_downloading: "Downloading",
                col_status_finish: "Completed",
                col_status_error: "Failed",
                col_status_pause: "Paused",
                col_status_delete: "Deleted",
                btn_action_start: "Start",
                btn_action_pause: "Pause",
                btn_action_delete: "Delete",
                errbox_title: "Download errors",
                errbox_btn_colse: "Close",
            },
            plugin: {
                title: "Plugins",
                plugin: "Plugin",
                manage: "Manage",
                type_language: "Language pack",
                type_search: "Search library",
                type_parse: "File parser",
                install_success: "Dependencies installed",
                need_install: "Requires installation",
                install_dependency: "Install dependencies",
            },
            setting: {
                title: "Settings",
                setting: "Settings",
                about_me: "About us",
                about_me_info: "iComic is an e-comic reader app. Enjoy your reading!",
                github: "Visit project",
                GitHub_PAT: "GitHub PAT",
                GitHub_PAT_Info: "Updates require GitHub API access. GitHub Personal Access token can bypass the 60 requests/hour limit",
                save: "Save",
                language: "Language",
                version: "Version",
                has_new_version: "New:{version}",
                check_new: "Check updates",
                update: "Update",
                cache: "Cache",
                clear_cache: "Clear cache",
                find_new_version: "New version found:[{version}]",
                current_version_is_higher: "Current version:[{version}] is the latest",
                current_version_is_new: "[{version}] is already the latest version"
            },
            update: {
                title: "Update",
                new_version: "New version",
                update_info: "Release notes",
                warning: "Backup your data! Backup your data! Backup your data!",
                warning_tip: "If your data isn't persistently stored, it will be lost after update (plugins, library, data)",
                warning_tip2: "Service may be temporarily down during update, check container logs in Docker for progress",
                releaseNotes: "Release notes",
                update: "Update"
            },
            server: {
                success: "Success",
                error: "Failed:{msg}",
                param_error: "Invalid parameters: {msg}",
                save_success: "Saved successfully",
                save_failed: "Save failed: {msg}",
                add_success: "Added successfully",
                no_file: "File doesn't exist",
                no_file_select: "No file selected",
                no_block: "File doesn't exist",
                no_config: "Configuration doesn't exist",
                no_plugin: "Plugin doesn't exist",
                no_plugin_select: "No plugin selected",
                no_library: "Library doesn't exist",
                plugin_cant_support_search: "This plugin doesn't support search",
                file_no_parse: "File not parsed",
                no_task: "Task doesn't exist",
                task_running: "Task already running",
                task_begin: "Task started",
                task_has: "Task already exists",
                task_pause: "Task paused",
                task_delete: "Task deleted",
                scan_complete: "Scan completed: {added} added, {deleted} deleted",
                scan_error: "Scan failed: {msg}",
                parse_begin: "Parsing started",
                parse_complete: "Parsing completed",
                parse_begin_multi: "Parsing started for {parse_count} files out of {file_count} total",
                install_success: "Dependencies installed successfully",
                install_error: "Dependency installation failed: {msg}",
                install_success_multi: "Dependencies installed: {install_count} plugins succeeded, {error_count} failed",
                install_error_multi: "Batch installation failed: {msg}"
            }
        };
    }
}
//global.Plugin = EnglishLanguagePlugin;
module.exports = {
    Plugin: EnglishLanguagePlugin
};