class EnglishLanguagePlugin extends LanguagePlugin {
    async getAllData() {
        return {
            home: {
                title: "iComic",
            },
            library: {
                title: "Library",
                empty: "Please scan the library first",
                scan: "Scan",
                continue: "Continue reading",
                not_parsed: "Not parsed",
                all_files: "All files",
                not_parsed_file: "This file has not been parsed yet",
                select_parse_plugin: "Please select a parsing plugin to parse",
                parse: "Parse",
                select_chapter: "Select chapter",
                select_parse_plugin: "Please select a parsing plugin to read",
                start_read: "Start reading",
                status_not_parsed: "Not parsed",
                status_parsing: "Parsing in progress",
                status_parsed: "Parsing completed",
                status_parse_failed: "Parsing failed",
            },
            download: {
                title: "Search",
                search: "Search",
                searching: "Searching for {query}",
                no_result: "No results found for {query}",
                standby: "There's always something you want to read",
                cover: "Cover",
                detail: "Details",
                col_title: "Title",
                col_description: "Description",
                add_to_col: "Operation",
                add_to_task: "Add",
            },
            reader: {
                loading_title: "Loading",
                loading_description: "Page is loading, please wait a moment!",
                loading_error_title: "Loading failed",
                loading_error_description: "Page loading failed: {error}",
            },
            download_task: {
                title: "Tasks",
                col_name: "Name",
                col_progress: "Progress",
                col_info: "Information",
                col_action: "Operation",
                col_status: "Status",
                col_status_wait: "Waiting for download",
                col_status_downloading: "Downloading",
                col_status_finish: "Download completed",
                col_status_error: "Download failed",
                col_status_pause: "Download paused",
                col_status_delete: "Deleted",
                btn_action_start: "Start",
                btn_action_pause: "Pause",
                btn_action_delete: "Delete",
                errbox_title: "Errors occurred during download",
                errbox_btn_colse: "Close",
            },
            plugin: {
                title: "Plugins",
                plugin: "Plugin",
                manage: "Manage",
                type_language: "Language pack",
                type_search: "Search library",
                type_parse: "File parser",
                install_success: "Dependencies installed successfully",
                need_install: "Dependencies required",
                install_dependency: "Install dependencies",
            },
            setting: {
                title: "Settings",
                setting: "Settings",
                about_me: "About us",
                about_me_info: "iComic is an electronic comic reading application. We wish you happy reading!",
                github: "Visit project",
                GitHub_PAT: "GitHub PAT",
                GitHub_PAT_Info: "Because updates need to access GitHub API, GitHub Personal Access token can bypass the GitHub API rate limit of 60 requests per hour",
                save: "Save",
                language: "Language",
                version: "Version",
                has_new_version: "New:{version}",
                check_new: "Check for updates",
                update: "Update",
                cache: "Cache",
                clear_cache: "Clear cache",
                find_new_version: "New version found:[{version}]",
                current_version_is_higher: "Current version:[{version}] is already the latest",
                current_version_is_new: "Version [{version}] is already the latest version",
                device_title: "Request device",
                device_desc:"The request headers that iComic carries when making requests",
            },
            update: {
                title: "Update",
                new_version: "New version",
                update_info: "Release notes",
                warning: "Please backup your data! Please backup your data! Please backup your data!",
                warning_tip: "If your data is not persistently saved, it will be lost after update (plugins, library, data)",
                warning_tip2: "Services may be shut down during update, please check the corresponding container logs in Docker for specific progress",
                releaseNotes: "Release notes",
                update: "Update",
                updating: "Updating",
                cancel:"Cancel",
                data_loss_warning: "Data loss warning",
                data_loss_warning2: "Confirm update? If data is not backed up or persisted, it will be lost after update (plugins, library, data)",
            },
            server: {
                success: "Processing successful",
                error: "Processing failed:{msg}",
                param_error: "Parameter error. {msg}",
                save_success: "Save successful",
                save_failed: "Save failed: {msg}",
                add_success: "Add successful",
                no_file: "File does not exist",
                no_file_select: "No file selected",
                no_block: "File does not exist",
                no_config: "Configuration does not exist",
                no_plugin: "Plugin does not exist",
                no_plugin_select: "No plugin selected",
                no_library: "Library does not exist",
                plugin_cant_support_search: "This plugin does not provide search",
                file_no_parse: "File not parsed",
                no_task: "Task does not exist",
                task_running: "Task is already running",
                task_begin: "Task started",
                task_has: "Task already exists",
                task_pause: "Task paused",
                task_delete: "Task deleted",
                scan_complete: "Scan completed: added {added}, deleted {deleted}",
                scan_error: "Scan failed: {msg}",
                parse_begin: "Parsing started",
                parse_complete: "Parsing completed",
                parse_begin_multi: "Started parsing {parse_count} files, total {file_count} files",
                install_success: "Dependencies installed successfully",
                install_error: "Dependencies installation failed: {msg}",
                install_success_multi: "Dependencies installed successfully: {install_count} plugins, failed: {error_count}",
                install_error_multi: "Batch dependencies installation failed: {msg}"
            }
        };
    }
}
//global.Plugin = EnglishLanguagePlugin;
module.exports = {
    Plugin: EnglishLanguagePlugin
};